# Generated by Django 5.0.14 on 2026-05-28 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpp_app', '0002_contactlead_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactlead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead liên hệ', 'verbose_name_plural': 'Leads liên hệ'},
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Khách mua lẻ'), ('business', 'Mua cho Doanh nghiệp / Trường học'), ('agency', 'Đăng ký làm đại lý')], default='business', max_length=50, verbose_name='Anh/chị đang là'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='message',
            field=models.TextField(verbose_name='Nội dung yêu cầu'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
